######################################################################
#  Project
######################################################################

BINARY		= uarthwfc
SRCFILES	= uarthwfc.c miniprintf.c

all: elf bin

include ../Makefile.incl

# End
