######################################################################
#  Project
######################################################################

BINARY		= miniblink
SRCFILES	= miniblink.c

all: elf bin

include ../Makefile.incl

# End
