######################################################################
#  Project Makefile
######################################################################

BINARY		= main
SRCFILES	= main.c rtos/heap_4.c rtos/list.c rtos/port.c rtos/queue.c rtos/tasks.c rtos/opencm3.c
LDSCRIPT	= stm32f103c8t6.ld

include ../../Makefile.incl
include ../Makefile.rtos

# End Makefile
