######################################################################
#  libwwg.a Makefile
######################################################################

.PHONY: clean clobber

all::
	$(MAKE) -$(MAKEFLAGS) -C ./src

clean:
	$(MAKE) -$(MAKEFLAGS) -C ./src clean

clobber:
	$(MAKE) -$(MAKEFLAGS) -C ./src clobber
	@rm -f libwwg.a

# End libwwg/Makefile
