######################################################################
#  Project
######################################################################

BINARY		= uart
SRCFILES	= uart.cpp miniprintf.c

all: elf bin

include ../Makefile.incl

# End
